### ISSUE TITLE
Add LWRP for VBoxManager

### ISSUE THREAD

**Issue by mhemesath** [jtimberman/virtualbox-cookbook#6]
It would be awesome to have LWRPs for the VBoxManager script. 

https://www.virtualbox.org/manual/ch08.html

**Comment by jtimberman** [comment]
Thanks for the idea. However, it seems to me that a large amount of this functionality is handled by [Vagrant](http://vagrantup.com), using the virtualbox driver. It's not really in scope for this cookbook to handle all aspects of managing Virtualbox, since my primary use case is to install Virtualbox such that it can be used with Vagrant, in fact.

I'd encourage you to write this kind of functionality in a new cookbook, perhaps named `vboxmanager` or similar.
